# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.xlt.idea.idea-themes
pluginName = xlt-themes
pluginRepositoryUrl = https://github.com/loosheng/intellij-vitesse-theme
# SemVer format -> https://semver.org
pluginVersion = 2.0.0

# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild = 253
pluginUntilBuild =

# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#configuration-intellij-extension
platformType = IU
platformVersion = 2026.2.2

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
# Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleWrapperVersion = 9.5.0

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false

# Disable Gradle Configuration Cache to avoid potential issues
# suppress inspection "UnusedProperty"
org.gradle.unsafe.configuration-cache = false
